#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name": "config-domain"}})
---
data:
  #@overlay/match missing_ok=True
  #@yaml/text-templated-strings
  (@= data.values.domain.name @): ""
