#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name": "config-network"}})
---
data:
  #@overlay/match missing_ok=True
  #@yaml/text-templated-strings
  domain-template: #@ data.values.domain.url_template
  
  #@overlay/match missing_ok=True
  ingress.class: contour.ingress.networking.knative.dev
