#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"metadata":{"name":"config-contour"}})
---
data:
  #@overlay/match missing_ok=True
  #@yaml/text-templated-strings
  visibility: |
    ExternalIP:
      class: contour
      service: (@= data.values.ingress.external.namespace @)/envoy
    ClusterLocal:
      class: contour
      service: (@= data.values.ingress.internal.namespace @)/envoy
