#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! When deploying the Knative Serving webhooks on AKS, we disable the AKS Admission Enforcer
#! so that AKS doesn't interfere with it.
#! See: https://learn.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces

#@ mutating_webhook = overlay.subset({"apiVersion": "admissionregistration.k8s.io/v1", "kind": "MutatingWebhookConfiguration"})
#@ validating_webhook = overlay.subset({"apiVersion": "admissionregistration.k8s.io/v1", "kind": "ValidatingWebhookConfiguration"})

#@overlay/match by=overlay.or_op(mutating_webhook,validating_webhook), expects="6+"
---
metadata:
  #@overlay/match missing_ok=True
  annotations:
    #@overlay/match missing_ok=True
    admissions.enforcer/disabled: "true"
