#@ load("@ytt:data", "data")

---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config

minimumRequiredVersion: 0.50.0

#! Rebase rules explicitly define how kapp should merge resources during an update.
#! See more about the resource merge method: https://carvel.dev/kapp/docs/latest/merge-method.
rebaseRules:

#! The HorizontalPodAutoscaler updates the replicas on Deployments.
#! We want to keep that configuration between upgrades.
- path: [spec, replicas]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: apps/v1, kind: Deployment}

#! Some Secrets are created empty and populated at install time by Knative Serving with TLS certificates.
#! We prefer the manifest configuration, but allow the one set on the cluster.
- paths:
  - [data, ca-cert.pem]
  - [data, server-cert.pem]
  - [data, server-key.pem]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - andMatcher:
      matchers:
      - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
      - hasNamespaceMatcher:
          names:
          - #@ data.values.namespace

#! These Secrets are created empty and populated by Knative Serving when internal-encryption is enabled.
#! They don't follow the standard naming conventions for TLS certificates, so we need a dedicate rule for them.
- path: [data]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Secret
      namespace: #@ data.values.namespace
      name: knative-serving-certs
  - kindNamespaceNameMatcher:
      kind: Secret
      namespace: #@ data.values.namespace
      name: serving-certs-ctrl-ca

#! By default, we want the changes applied on-cluster to the ConfigMaps
#! to be persisted between upgrades.
- path: [data]
  type: copy
  sources: [existing, new]
  resourceMatchers:
  - andMatcher:
      matchers:
      - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}
      - hasNamespaceMatcher:
          names:
          - #@ data.values.namespace

#! The 'visibility' property in the 'config-contour' ConfigMap is configurable via overlay,
#! so we want to use the new values and discard any change applied directly to the cluster.
- path: [data, visibility]
  type: remove
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: ConfigMap
      namespace: #@ data.values.namespace
      name: config-contour
- path: [data, visibility]
  type: copy
  sources: [new]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: ConfigMap
      namespace: #@ data.values.namespace
      name: config-contour

#! When upgrading, we prefer the changes applied to the ConfigMaps on the cluster by default,
#! but we want to get the new example values from the new version.
- path: [data, _example]
  type: remove
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}
- path: [data, _example]
  type: copy
  sources: [new]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}

#! These webhook configurations are populated by Knative Serving at install time.
#! We prefer the manifest configuration, but allow the one set on the cluster.
- paths:
  - [webhooks, {allIndexes: true}, clientConfig, service, path]
  - [webhooks, {allIndexes: true}, clientConfig, service, port]
  - [webhooks, {allIndexes: true}, matchPolicy]
  - [webhooks, {allIndexes: true}, namespaceSelector]
  - [webhooks, {allIndexes: true}, objectSelector]
  - [webhooks, {allIndexes: true}, reinvocationPolicy]
  - [webhooks, {allIndexes: true}, rules]
  type: copy
  sources: [new, existing]
  resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: admissionregistration.k8s.io/v1, kind: MutatingWebhookConfiguration}
  - apiVersionKindMatcher: {apiVersion: admissionregistration.k8s.io/v1, kind: ValidatingWebhookConfiguration}
