apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: knative-serving.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: knative-serving.packages.kadras.io
  releaseNotes: https://github.com/knative/serving/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          description: The namespace where to install Knative Serving
          default: knative-serving
        domain:
          type: object
          additionalProperties: false
          description: DNS configuration
          properties:
            name:
              type: string
              description: Your own domain name
              default: 127.0.0.1.sslip.io
            url_template:
              type: string
              description: The domain template to use when creating new services
              default: '{{.Name}}.{{.Namespace}}.{{.Domain}}'
        ingress:
          type: object
          additionalProperties: false
          description: Ingress configuration
          properties:
            external:
              type: object
              additionalProperties: false
              description: Configuration for the external Ingress controller
              properties:
                namespace:
                  type: string
                  description: The namespace where the external Ingress controller is installed
                  default: projectcontour
            internal:
              type: object
              additionalProperties: false
              description: Configuration for the internale Ingress controller
              properties:
                namespace:
                  type: string
                  description: The namespace where the internal Ingress controller is installed
                  default: projectcontour
        tls:
          type: object
          additionalProperties: false
          description: Configuration for automatic TLS certificates
          properties:
            certmanager:
              type: object
              additionalProperties: false
              description: Configuration for integrating with cert-manager for certificate issuing
              properties:
                clusterissuer:
                  type: string
                  description: Provide a cluster issuer if you want to enable auto-TLS
                  default: ""
        scaling:
          type: object
          additionalProperties: false
          description: Configuration for the Knative autoscaler
          properties:
            initial_scale:
              type: string
              description: The initial target scale of a revision after creation
              default: "1"
            min_scale:
              type: string
              description: The minimum scale of a revision
              default: "0"
            max_scale:
              type: string
              description: The maximum scale of a revision. If set to 0, the revision has no maximum scale.
              default: "0"
            allow_zero_initial_scale:
              type: string
              description: Whether either the initial_scale config or the 'autoscaling.knative.dev/initial-scale' annotation can be set to 0
              default: "true"
            scale_down_delay:
              type: string
              description: The amount of time that must pass at reduced concurrency before a scale down decision is applied. If 0s, no delay.
              default: 0s
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: knative-serving.packages.kadras.io
spec:
  categories:
  - serverless
  - deployment
  displayName: knative-serving
  longDescription: Knative Serving builds on Kubernetes to support deploying and serving
    of applications and functions as serverless containers
  maintainers:
  - name: Thomas Vitale
  providerName: Arktonix
  shortDescription: Serverless platform on Kubernetes

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: knative-serving
spec:
  packageRef:
    refName: knative-serving.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
